# Generated by Django 3.1.7 on 2021-03-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210320_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='highest',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
