# Generated by Django 3.1.7 on 2021-03-22 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bids_highest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.Categories'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
